/**
 * Generates all valid substat roll sum lookup tables.
 *
 * For each artifact rarity and substat type, computes every unique sum
 * reachable by combining 1–N rolls (mixed tiers allowed), then writes
 * a sorted array to src/generated/valid-roll-sums.ts.
 *
 * Run: bun run generate:rolls
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ── Import roll tables directly from source ──────────────────────────

// We dynamically import the artifact types file via its transpiled form.
// To avoid coupling to the build system, we just read and eval the constants.

const artifactSrc = readFileSync(resolve(ROOT, 'src/types/artifact.ts'), 'utf-8')

function extractRollTable(src: string, varName: string): Record<string, number[]> {
  // Match: export const VARNAME: ... = { ... }
  const re = new RegExp(
    `export\\s+const\\s+${varName}\\s*(?::[^=]*)=\\s*\\{([^}]+)\\}`,
    's',
  )
  const match = src.match(re)
  if (!match?.[1]) throw new Error(`Could not extract ${varName} from artifact.ts`)

  const body = match[1]
  const table: Record<string, number[]> = {}

  // Match each entry: 'Stat Name': [1.23, 4.56, ...] or StatName: [...]
  const entryRe = /(?:'([^']+)'|(\w+))\s*:\s*\[([^\]]+)\]/g
  let m: RegExpExecArray | null
  while ((m = entryRe.exec(body)) !== null) {
    const key = m[1] ?? m[2]!
    const values = m[3]!.split(',').map((v) => parseFloat(v.trim()))
    table[key] = values
  }

  return table
}

const ROLL_TABLES: Record<number, Record<string, number[]>> = {
  5: extractRollTable(artifactSrc, 'SUBSTAT_ROLLS'),
  4: extractRollTable(artifactSrc, 'SUBSTAT_ROLLS_4STAR'),
  3: extractRollTable(artifactSrc, 'SUBSTAT_ROLLS_3STAR'),
  2: extractRollTable(artifactSrc, 'SUBSTAT_ROLLS_2STAR'),
  1: extractRollTable(artifactSrc, 'SUBSTAT_ROLLS_1STAR'),
}

// Max rolls per rarity (initial roll + bonus rolls at every 4 levels)
const MAX_ROLLS: Record<number, number> = {
  5: 6, // levels 0-20: rolls at 4,8,12,16,20 + initial
  4: 5, // levels 0-16: rolls at 4,8,12,16 + initial
  3: 4, // levels 0-12: rolls at 4,8,12 + initial
  2: 2, // levels 0-4: roll at 4 + initial
  1: 2, // levels 0-4: roll at 4 + initial
}

// ── Compute all valid sums ───────────────────────────────────────────

function computeValidSums(rolls: number[], maxRolls: number): number[] {
  // BFS/iterative: track reachable sums at each roll count
  let current = new Set<number>()
  const allSums = new Set<number>()

  // 1 roll
  for (const r of rolls) {
    const rounded = Math.round(r * 100) / 100
    current.add(rounded)
    allSums.add(rounded)
  }

  // 2..maxRolls
  for (let rollNum = 2; rollNum <= maxRolls; rollNum++) {
    const next = new Set<number>()
    for (const sum of current) {
      for (const r of rolls) {
        const newSum = Math.round((sum + r) * 100) / 100
        next.add(newSum)
        allSums.add(newSum)
      }
    }
    current = next
  }

  return [...allSums].sort((a, b) => a - b)
}

// ── Generate output ──────────────────────────────────────────────────

// Hash the roll table source sections for staleness detection
function computeSourceHash(): string {
  const hash = createHash('sha256')
  for (const varName of [
    'SUBSTAT_ROLLS',
    'SUBSTAT_ROLLS_4STAR',
    'SUBSTAT_ROLLS_3STAR',
    'SUBSTAT_ROLLS_2STAR',
    'SUBSTAT_ROLLS_1STAR',
  ]) {
    const re = new RegExp(
      `export\\s+const\\s+${varName}\\s*(?::[^=]*)=\\s*\\{[^}]+\\}`,
      's',
    )
    const match = artifactSrc.match(re)
    if (match?.[0]) hash.update(match[0])
  }
  return hash.digest('hex').slice(0, 16)
}

const STAT_TYPES = [
  'CRIT Rate',
  'CRIT DMG',
  'ATK%',
  'ATK',
  'HP%',
  'HP',
  'DEF%',
  'DEF',
  'Elemental Mastery',
  'Energy Recharge',
]

function formatArray(arr: number[]): string {
  // Wrap lines at ~90 chars
  const parts: string[] = []
  let line = ''
  for (const v of arr) {
    const s = String(v)
    if (line.length + s.length + 2 > 80) {
      parts.push(line)
      line = s + ', '
    } else {
      line += s + ', '
    }
  }
  if (line) parts.push(line.replace(/, $/, ''))
  return parts.map((l) => `      ${l}`).join('\n')
}

function generate(): string {
  const sourceHash = computeSourceHash()
  const lines: string[] = [
    `// AUTO-GENERATED by scripts/generate-roll-tables.ts — do not edit manually.`,
    `// Run \`bun run generate:rolls\` to regenerate.`,
    `// source-hash: ${sourceHash}`,
    ``,
    `import type { ArtifactRarity, SubstatType } from '@/types/artifact'`,
    ``,
    `const VALID_ROLL_SUMS: Record<ArtifactRarity, Record<SubstatType, number[]>> = {`,
  ]

  for (const rarity of [1, 2, 3, 4, 5]) {
    const table = ROLL_TABLES[rarity]!
    const maxRolls = MAX_ROLLS[rarity]!
    lines.push(`  ${rarity}: {`)
    for (const stat of STAT_TYPES) {
      const rolls = table[stat]
      if (!rolls) {
        console.warn(`Warning: no rolls for rarity ${rarity}, stat "${stat}"`)
        continue
      }
      const sums = computeValidSums(rolls, maxRolls)
      const key = stat.includes(' ') || stat.includes('%') ? `'${stat}'` : stat
      lines.push(`    ${key}: [`)
      lines.push(formatArray(sums))
      lines.push(`    ],`)
    }
    lines.push(`  },`)
  }

  lines.push(`}`)
  lines.push(``)
  lines.push(`export default VALID_ROLL_SUMS`)
  lines.push(``)

  return lines.join('\n')
}

// ── Main ─────────────────────────────────────────────────────────────

const output = generate()
const outPath = resolve(ROOT, 'src/generated/valid-roll-sums.ts')
writeFileSync(outPath, output, 'utf-8')

// Count total entries for summary
let totalEntries = 0
for (const rarity of [1, 2, 3, 4, 5]) {
  const table = ROLL_TABLES[rarity]!
  const maxRolls = MAX_ROLLS[rarity]!
  for (const stat of STAT_TYPES) {
    const rolls = table[stat]
    if (rolls) totalEntries += computeValidSums(rolls, maxRolls).length
  }
}

console.log(`Generated ${outPath}`)
console.log(`  ${totalEntries} total valid roll sums across 5 rarities × 10 stats`)
